apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: 'false'
    flux.weave.works/locked: 'true'
  name: hello-world-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello1
    spec:
      containers:
      - image: openebs/flux-test:master-a000001
        name: flux-test
        ports:
        - containerPort: 8080
